version: 2


models:
  - name: vw_exercicio_01_aula_05
    description: "Modelo referente a view que foi criada no exercício 01 da Aula 05"
    columns:
      - name: id_registro
        description: "Chave Primária da Tabela contendo um hash MD5 gerado pela surrogate_key"
        tests:
          - unique
          - not_null
      - name: cidade
        description: "Nome da cidade da coleta de dados de combustíveis"
      - name: produto
        description: "Tipo de produto Etanol ou Gasolina"
      - name: valor_revenda
        description: "Valor da Revenda do Produto"
      - name: data_coleta
        description: "Data da Coleta dos Preços"
